apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/jinqi7/olm-operator-konflux-sample?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: multiarch-fbc
    appstudio.openshift.io/component: gatekeeper-operator
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-operator-on-pull-request
  namespace: jinqi-1-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/jinqi-1-tenant/gatekeeper-operator:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.gatekeeper-operator
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
  #     - linux/ppc64le
  #     - linux/s390x
  pipelineRef:
    name: build-pipeline
